name: Pytest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - shell: bash
      env:
        SECRET: ${{ secrets.SECRET }}
        SMTP_HOST: ${{ secrets.SMTP_HOST }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
      run: |
        python start.py & pytest
